### ISSUE TITLE
Villagers follow emeralds item list is hardcoded instead of pulled from a tag.

### ISSUE THREAD

**Issue by James103** [Hyperbean18/Villagers-Follow-Emeralds-Fabric#1]
https://github.com/Hyperbean18/Villagers-Follow-Emeralds-Fabric/blob/5cd19cffdcc23fd5b97b6802498a437c0aaa1257/src/main/java/matjojo/mixin/villagerInitMixin.java#L25-L27

As shown above, the list of items that the player needs to hold in order for the villager to follow that player is hardcoded into the mod itself, with no configuration whatsoever. To fix this, I would like to suggest that the list be instead stored in a tag (such as `villagers_follow:emerald_items`) and that the list of items is queried from that tag instead of being hardcoded.

The default contents of such a tag would be as follows in order to preserve existing behavior:
```
minecraft:emerald_block
#minecraft:emerald_ores
```

**Comment by Hyperbean18** [comment]
I'll look into it this weekend (no promises tho)

**Comment by Hyperbean18** [comment]
Fixed thanks to SirEnder125
